[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "pytelegrambotapi>=4.29.1",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
]
